Pin urllib3 version to 1.26.16
That is the last version of the v1 series, which uses OpenSSL
1.0.2. If we don't pin it, then v2 is installed, which requires
OpenSSL 1.1.1+, and we get this error:
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips  26 Jan 2017'. See: https://github.com/urllib3/urllib3/issues/2168

This pinning can be removed when upgrading to Alma9, which has a
newer version of OpenSSL.